const LangueList = [ 
  'A+ ',
  ' Ada ',
  ' 汇编语言',
  ' B ',
  'Brainfuck',
  ' C ',
  ' C++ ',
  'C++/CLI',
  ' Cg ',
  ' COBOL ',
  ' Eiffel ',
  ' Erlang ',
  ' FORTRAN ',
  ' IronPython ',
  ' Java ',
  ' JRuby ',
  ' Jython ',
  ' LISP ',
  ' Oberon ',
  'Objective-C',
  'Ocaml',
  ' Pascal ',
  ' Perl ',
  ' Powerbuilder ',
  ' Python ',
  ' QBASIC ',
  ' R ',
  ' REXX ',
  ' Ruby ',
  ' Self ',
  '  Smalltalk ',
  ' SQL ',
  ' Tcl/Tk ',
  ' Visual Basic ',
  ' PHP ',
  ' C# ',
  ' F# ',
  ' J# ',
  'Visual Basic .NET',
  '易语言',
  'ActionScript ',
  ' JavaScript ',
  ' JScript ',
  'Nuva',
  ' PostScript ',
  ' VBScript ',
  ' lua APL/J ',
  ' Haskell ',
  ' Logo ',
  ' ML ',
  'pascal',
  'Prolog ',
  ' Scheme ',
  ' SAC ALGOL ',
  ' BASIC',
  ' Clipper ',
  ' Forth ',
  ' Modula-2/Modula-3 ',
  ' MUMPS ',
  ' PL/I ',
  ' Simula' ]